--- #YAML:1.0
name:               String-RewritePrefix
version:            0.005
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Sub::Exporter:  0
    Test::More:     0.47
resources:
    Repository:  http://github.com/rjbs/string-rewriteprefix
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
